### ISSUE TITLE
Strojový překlad plevelí výsledky vyhledávání špatně čitelným obsahem.

### ISSUE THREAD

**Issue by v6ak** [dotnet/docs.cs-cz#10]
Strojový překlad zapleveluje výsledky vyhledávání. Nemám problém, když mi Google najde relevantní výsledky v češtině – pokud ovšem je to čeština a ne příšernost vytvořená automatickým překladem. Bohužel, Google mi často tuto příšernost vyhodí jako první.  Trvalo mi nějaký čas najít, tlačítko „Číst v angličtině“. Zpočátku moji pozornost upoutala spíše výrazná lišta „ This article was translated by machine. …“ se slibně vypadajícím tlačítkem „Zakázat“. Bohužel po přečtení nebo kliknutí ale zjistím, že to zakazuje něco jiného…

I když vypnu ten automatický strojový překlad do češtiny, dole je „Náš nový systém zpětné vazby je založen na problémech s GitHubem.“, což vypadá jako strojový překlad, jen to nelze tak snadno vypnout ani přečíst si originál.

Vyřešil jsem to nakonec pomocí https://gist.github.com/v6ak/61c5d23b5b50d62d33818eb8a3fca968

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: f950f479-532b-ab38-a676-653495777197
* Version Independent ID: 30fa2c1a-86bd-e683-3e6f-8a268f4dc4e5
* Content: [Postupy: Zobrazení certifikátů pomocí modulu snap-in konzoly MMC](https://docs.microsoft.com/cs-cz/dotnet/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in)
* Content Source: [docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md](https://github.com/dotnet/docs.cs-cz/blob/live/docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by LisandroSu** [comment]
Zpráva pro uživatele @v6ak : 

Dobrý den, děkujeme vám za váš názor. Příslušná stránka byla přeložena strojově, takže výsledný text není vždy dokonale srozumitelný. Nedávno jsme na pravou stranu přidali odkaz na verzi v angličtině, která umožňuje přepnutí na originál bez nutnosti změny nastavení jazyka. 

S pozdravem 
Mezinárodní tým Microsoft DOCS
