### ISSUE TITLE
Bad translation / špatný překlad

### ISSUE THREAD

**Issue by maruniluk** [dotnet/docs.cs-cz#11]
Please, do not translate the keywords. It makes it useless. 
Nepřekládejte prosím klíčová slova. Příkaz "pro" mi moc nepomůže (místo "for")

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: e825860b-5966-26c4-72bb-9df62c7329f0
* Version Independent ID: 4cf67a2a-173d-7f55-910a-cf883fe4086e
* Content: [C# pro příkaz](https://docs.microsoft.com/cs-cz/dotnet/csharp/language-reference/keywords/for)
* Content Source: [docs/csharp/language-reference/keywords/for.md](https://github.com/dotnet/docs.cs-cz/blob/live/docs/csharp/language-reference/keywords/for.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @maruniluk 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @maruniluk 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
