### ISSUE TITLE
Bad Czech translation

### ISSUE THREAD

**Issue by Dokans** [dotnet/docs.cs-cz#15]
Translation of key words "checked" and "unchecked" is translated as "zaškrtnuto" and "nezaškrtunto", ut it should be translated as "zkontrolováno" and "nezkotrolováno". Because "zaškrtnuto" can also be translated as "marked" which dosent make sense in thsi context

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: afbca89d-149d-f904-bbec-71446bfa5506
* Version Independent ID: 6ce3ce8d-a80c-81aa-2d16-b2fec0d8a89a
* Content: [Zaškrtnuto a nezaškrtnuto - C# odkaz](https://docs.microsoft.com/cs-cz/dotnet/csharp/language-reference/keywords/checked-and-unchecked#feedback)
* Content Source: [docs/csharp/language-reference/keywords/checked-and-unchecked.md](https://github.com/dotnet/docs.cs-cz/blob/live/docs/csharp/language-reference/keywords/checked-and-unchecked.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Dokans
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Dokans 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pageshttps://docs.microsoft.com/cs-cz/dotnet/csharp/language-reference/keywords/checked-and-unchecked#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
