### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by Wolpres** [dotnet/docs.cs-cz#18]
Some keywords in this list are also translated on czech version of this documentation page

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: fa5712fd-a965-e2a9-5b1c-0b295d5e8ccd
* Version Independent ID: 4b943400-309d-0437-5513-0533456297f0
* Content: [Klíčová slova jazyka C#](https://docs.microsoft.com/cs-cz/dotnet/csharp/language-reference/keywords/)
* Content Source: [docs/csharp/language-reference/keywords/index.md](https://github.com/dotnet/docs.cs-cz/blob/live/docs/csharp/language-reference/keywords/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Wolpres
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Wolpres 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Microsoft DOCS International Team
Kind regards,
