### ISSUE TITLE
PowerShell script does not work

### ISSUE THREAD

**Issue by karelkral** [dotnet/docs.cs-cz#5]
Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\" | Get-ItemPropertyValue -Name Release | ForEach-Object { $_ -ge 394802 } 
ForEach-Object { $_ -ge 394802 }
The term 'Get-ItemPropertyValue' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.At
line:1 char:76
+ Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\" |
Get-I ...
+
~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ItemPropertyValue:String) [
   ], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Postupy: zjištění nainstalovaných verzí rozhraní .NET Framework](https://docs.microsoft.com/cs-cz/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#ps_a)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs.cs-cz/blob/live/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
Where did you get that code? I can't find it on the page you linked to, only on a comment for it: https://github.com/dotnet/docs/issues/7358.

Regarding your actual question, as far as I can tell, `Get-ItemPropertyValue` is only supported in PowerShell 5.0 or newer. What version of PowerShell are you using?

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #7607](https://github.com/dotnet/docs/issues/7607) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @karelkral ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/7607.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by karelkral** [comment]
I get this code right from Microsoft doc where I have reported the issue: https://docs.microsoft.com/cs-cz/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#ps_a
