### ISSUE TITLE
Bohužel zcela nepoužitelné

### ISSUE THREAD

**Issue by Dedecekhribecek** [dotnet/docs.cs-cz#8]
Tento překlad do českého jazyka je bohužel zcela zavádějící a mnohdy nepochopitelný. Kdo umí anglicky přepíná na angličtinu. Bohužel.
Tato výtka se týká hlavně kapitoly vlastnosti statických konstruktorů.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: aa3ed1c5-1f79-9234-beec-b5771c3fb3c0
* Version Independent ID: ac4f6361-70a7-fb43-101e-c12044f60896
* Content: [Statické konstruktory (Průvodce programováním v C#)](https://docs.microsoft.com/cs-cz/dotnet/csharp/programming-guide/classes-and-structs/static-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/static-constructors.md](https://github.com/dotnet/docs.cs-cz/blob/live/docs/csharp/programming-guide/classes-and-structs/static-constructors.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Zpráva pro uživatele @Dedecekhribecek: 

Dobrý den, děkujeme vám za váš názor. Příslušná stránka byla přeložena strojově, takže výsledný text není vždy dokonale srozumitelný. Nedávno jsme na pravou stranu přidali odkaz na verzi v angličtině, která umožňuje přepnutí na originál bez nutnosti změny nastavení jazyka. 

S pozdravem 
Mezinárodní tým Microsoft DOCS
